name: flutter_crm_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_auth:
  flutter_bloc:
  sqflite:
  http:
  path:
  path_provider:
  provider:
  image_picker:

flutter_icons: android:"launcher_icon"
  ios:true
  image_path:"assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
